name : Flatcraft
version: Alpha-0.1
main: me.xxsniperzzxxsd.flatcraft.Main //I hate the file route, do you?
author: cwk4229
description: Custom plugin made for the Flatcraft Network
commands:
    Flatcraft:
        usage: /flatcraft
        description: A bit about Flatcraft server.
