name : flatcraft
version: 0.1
main: me.xxsniperzzxxsd.flatcraft.Main
author: xdevilx04
description: Nothing at this point
commands:
    Flatcraft:
        usage: /Command
        description: My first command!